Case Demonstration case for MMP simulation chain
Geometry file generated by GTM-X
node id given
element id given
coordinates
   8
     101 0.00000E+00 0.00000E+00 0.00000E+00
     102 1.00000E+00 0.00000E+00 0.00000E+00
     103 1.00000E+00 1.00000E+00 0.00000E+00
     104 0.00000E+00 1.00000E+00 0.00000E+00
     105 0.00000E+00 0.00000E+00 1.00000E+00
     106 1.00000E+00 0.00000E+00 1.00000E+00
     107 1.00000E+00 1.00000E+00 1.00000E+00
     108 0.00000E+00 1.00000E+00 1.00000E+00
     
part 1
D_FLOW
hexa8
    1
     100     101     102     103     104     105     106    107      108    
part 2
B_D_FLOW
quad4
    2
      10     101     102     103     104
      11     105     106     107     108